spring:
  application:
    name: camel-poc
  datasource:
    url: jdbc:mysql://localhost:3306/job_db?useSSL=false&allowPublicKeyRetrieval=true
    username: local_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
